# Generated by Django 4.1.7 on 2023-04-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('cloths', 'CLOTHS'), ('GROCERY', 'grocery'), ('others', 'OTHERS')], default=None, max_length=10),
        ),
    ]
